// Mocks generated by Mockito 5.4.4 from annotations
// in finalproject/test/unit_test/auth_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;

import 'package:dartz/dartz.dart' as _i2;
import 'package:finalproject/core/failure/failure.dart' as _i5;
import 'package:finalproject/features/auth/domain/entity/auth_entity.dart'
    as _i7;
import 'package:finalproject/features/auth/domain/usecases/auth_usecase.dart'
    as _i3;
import 'package:finalproject/features/auth/presentation/navigator/login_navigator.dart'
    as _i8;
import 'package:finalproject/features/auth/presentation/navigator/register_navigator.dart'
    as _i9;
import 'package:finalproject/features/profile/domain/entity/profile_entity.dart'
    as _i15;
import 'package:finalproject/features/profile/domain/repository/profile_repository.dart'
    as _i14;
import 'package:finalproject/features/rateAndReview/domain/entity/review_entity.dart'
    as _i13;
import 'package:finalproject/features/rateAndReview/domain/repository/review_repository.dart'
    as _i12;
import 'package:finalproject/features/serviceDetailpage/domain/entity/service_detail_entity.dart'
    as _i11;
import 'package:finalproject/features/serviceDetailpage/domain/repository/service_detail_repository.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthUseCase extends _i1.Mock implements _i3.AuthUseCase {
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> uploadProfilePicture(
          _i6.File? file) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfilePicture,
          [file],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #uploadProfilePicture,
            [file],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, String>>.value(
                _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #uploadProfilePicture,
            [file],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> registerUser(
          _i7.AuthEntity? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [user],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #registerUser,
            [user],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #registerUser,
            [user],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> loginUser(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginUser,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #loginUser,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #loginUser,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> logoutUser() => (super.noSuchMethod(
        Invocation.method(
          #logoutUser,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #logoutUser,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #logoutUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}

/// A class which mocks [LoginViewNavigator].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginViewNavigator extends _i1.Mock
    implements _i8.LoginViewNavigator {
  @override
  void openDashboardView() => super.noSuchMethod(
        Invocation.method(
          #openDashboardView,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void openLoginView() => super.noSuchMethod(
        Invocation.method(
          #openLoginView,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RegisterViewNavigator].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterViewNavigator extends _i1.Mock
    implements _i9.RegisterViewNavigator {}

/// A class which mocks [IServiceDetailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIServiceDetailRepository extends _i1.Mock
    implements _i10.IServiceDetailRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i11.ServiceDetailEntity>> getPosts(
          String? serviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [serviceId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i11.ServiceDetailEntity>>.value(
                _FakeEither_0<_i5.Failure, _i11.ServiceDetailEntity>(
          this,
          Invocation.method(
            #getPosts,
            [serviceId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i11.ServiceDetailEntity>>.value(
                _FakeEither_0<_i5.Failure, _i11.ServiceDetailEntity>(
          this,
          Invocation.method(
            #getPosts,
            [serviceId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i11.ServiceDetailEntity>>);
}

/// A class which mocks [ReviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewRepository extends _i1.Mock implements _i12.ReviewRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> createReview(
    String? serviceId,
    double? rating,
    String? comment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReview,
          [
            serviceId,
            rating,
            comment,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #createReview,
            [
              serviceId,
              rating,
              comment,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #createReview,
            [
              serviceId,
              rating,
              comment,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i13.ReviewEntity>>> getServiceReviews(
          String? serviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServiceReviews,
          [serviceId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i13.ReviewEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i13.ReviewEntity>>(
          this,
          Invocation.method(
            #getServiceReviews,
            [serviceId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i13.ReviewEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i13.ReviewEntity>>(
          this,
          Invocation.method(
            #getServiceReviews,
            [serviceId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i13.ReviewEntity>>>);
}

/// A class which mocks [IProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProfileRepository extends _i1.Mock
    implements _i14.IProfileRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i15.ProfileEntity>> getUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i15.ProfileEntity>>.value(
                _FakeEither_0<_i5.Failure, _i15.ProfileEntity>(
          this,
          Invocation.method(
            #getUser,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i15.ProfileEntity>>.value(
                _FakeEither_0<_i5.Failure, _i15.ProfileEntity>(
          this,
          Invocation.method(
            #getUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i15.ProfileEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> editProfile(
          _i15.ProfileEntity? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [profile],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #editProfile,
            [profile],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #editProfile,
            [profile],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
